# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 16:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kai.genKey


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='API')),
            ],
            options={
                'verbose_name': 'API',
            },
        ),
        migrations.CreateModel(
            name='APIgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='API Group')),
            ],
            options={
                'verbose_name': 'API Group',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=kai.genKey.getKey, max_length=30, verbose_name='User Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True, verbose_name='Date')),
                ('time', models.TimeField(auto_now_add=True, null=True, verbose_name='Time')),
                ('success', models.BooleanField(default=False, verbose_name='Request State')),
                ('properties', models.CharField(blank=True, max_length=500, verbose_name='Request Properties')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kai.API')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Request',
            },
        ),
        migrations.AddField(
            model_name='api',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kai.APIgroup'),
        ),
    ]
